export let variables = { 
playerFirst: null,
playerSecond: null,
bulletsPlayerFirst: null,
bulletsPlayerSecond: null,
bulletTime: 0,
cursors: null,
fireButtonPlayerFirst: null,
fireButtonPlayerSecond: null,
explosions: null,
explosionSoud: null,
starfield: null,
score: 0,
scoreString: '',
scoreText: null,
livesPlayerFirst: null,
livesPlayerSecond: null,
firingTimer: 0,
stateText: null,
livingEnemies: [],
w: 800,
h: 600,
choiseLabel: null,
playLabel: null,
gameStatus: null,
about: null,
aboutLabel: null,
upWASD  : null,
downWASD : null,
leftWASD : null,
rightWASD : null,
}
